name: Playwright Tests
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "*/30 * * * *"

# TODO: use a fast and full approach to CI
jobs:
  playwright:
    uses: andreaTP/apicurio-gh-workflows/.github/workflows/playwright.yaml@playwright
    with:
      os: ubuntu-latest
      notify-on-failure: false
    secrets:
      username: ${{ secrets.RH_USERNAME }}
      password: ${{ secrets.RH_PASSWORD }}
